### ISSUE TITLE
[bug] can't parse a negative number

### ISSUE THREAD

**Issue by ilfey** [AgentRBY/HL_Bot#8]
Command:
![image](https://user-images.githubusercontent.com/68865207/230630316-60812b15-ddd0-4792-a43e-2c769387ccf8.png)

![image](https://user-images.githubusercontent.com/68865207/230630397-9a4e6404-0e80-410a-9155-907b7b5230b9.png)

**Comment by AgentRBY** [comment]
Fixed in bf9f729
